### ISSUE TITLE
コマンドラインからチャンネル開くやつがバグってるの直す

### ISSUE THREAD

**Issue by kamecha** [kamecha/traqVimPractice#88]
現状下みたいなエラーが出るので直しとく
```
:Traq channel open #gps/times/kamecha
Error detected while processing function command#call[8]..command#channel[3]..denops#request[1]..denops#_
internal#server#chan#request[6]..denops#_internal#rpc#nvim#request:
line    1:
Error invoking 'invoke' on channel 4 (denops):
Error: Failed to call 'timeline' API in 'traqvim': The value must be string
    at Plugin.call (file:///home/kamecha_linux/.cache/dein/nvim/repos/github.com/vim-denops/denops.vim/de
nops/@denops-private/service.ts:175:13)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Service.#dispatch (file:///home/kamecha_linux/.cache/dein/nvim/repos/github.com/vim-denops/d
enops.vim/denops/@denops-private/service.ts:88:12)
    at async Service.dispatch (file:///home/kamecha_linux/.cache/dein/nvim/repos/github.com/vim-denops/de
nops.vim/denops/@denops-private/service.ts:93:14)
    at async dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/dispatcher.ts:36:12)
    at async Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:244:22)
    at async Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:271:33)
```

**Comment by kamecha** [comment]
コマンドラインでチャンネル名の補完がされないのは辛いので、補完できるようにもしとく
